{
  :schema => {
    "$schema" => "http://www.archivesspace.org/archivesspace.json",
    "version" => 1,
    "type" => "object",
    "properties" => {
      "identifier" => {"type" => "string"},
      "date" => {"type" => "date"},
      "digital" => {"type" => "string"},
      "standard" => {"type" => "string"},
      "generations" => {"type" => "string"},
      "colors" => {"type" => "string"},
      "duration" => {"type" => "string"},
      "data_rate" => {"type" => "string"},
      "tracks" => {"type" => "string"},
      "channel_configuration" => {"type" => "string"},
      "alternative_modes" => {"type" => "string"},
      "video_track_standard" => {"type" => "string"},
      "audio_track_standard" => {"type" => "string"},
      "video_track_encoding" => {"type" => "string"},
      "audio_track_encoding" => {"type" => "string"},
      "video_track_data_rate" => {"type" => "string"},
      "audio_track_data_rate" => {"type" => "string"},
      "frame_rate" => {"type" => "string"},
      "playback_speed" => {"type" => "string"},
      "sampling_rate" => {"type" => "string"},
      "video_bit_depth" => {"type" => "string"},
      "audio_bit_depth" => {"type" => "string"},
      "frame_size" => {"type" => "string"},
      "aspect_ratio" => {"type" => "string"},
      "video_track_time_start" => {"type" => "string"},
      "audio_track_time_start" => {"type" => "string"},
      "video_track_duration" => {"type" => "string"},
      "audio_track_duration" => {"type" => "string"},
    },
  },
}
